trigger:
  branches:
    include:
      - main #123

pool:
  vmImage: 'ubuntu-22.04'

schedules:
- cron: "0 8 * * *"
  displayName: Daily UTC build
  branches:
    include:
    - main
  always: true

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'

- bash: |
    pip install dbt-snowflake
    pip list
    dbt debug --profiles-dir ./azdevops
    python run-dbt.py
  displayName: 'Install and run dbt'
  env:
    SNOWFLAKE_PASSWORD: $(SNOWFLAKE_PASSWORD)
    SNOWFLAKE_USERNAME: $(SNOWFLAKE_USERNAME)
    SNOWFLAKE_SCHEMA: $(SF_SANDBOX_SCHEMA)